MAX_THREADS = 12

TYPES_SEARCH = ['PARALLEL', 'CONCURRENT', 'LINEAR']
TYPES_PERIOD = ['YEAR', 'SEMESTER', 'QUARTER', 'TRIMESTER']
TYPE_SEARCH = TYPES_SEARCH[0] # 0 - PARALLEL, 1 - CONCURRENT. 2 - LINEAR
TYPE_PERIOD = TYPES_PERIOD[3] # 0 - YEAR, 1 - SEMESTER, 2 - QUARTER, 3 - TRIMESTER