PRINTER_FORM_ID_PRE_FIX = 'form:j_id_jsp_1439633680_513:'
# PRINTER_FORM_ID_PRE_FIX = "//*[matches(@id, 'form:j_id_jsp_.*:imprimir')]"
PRINTER_FORM_ID_POS_FIX = ':imprimir'

VIEW_FORM_ID_PRE_FIX = 'form:j_id_jsp_1439633680_513:'
VIEW_FORM_ID_POS_FIX = ':visualizar'

OBJECT_FORM_ID = 'j_id_jsp_345370874_1:tbOds:tbody_element'

ID_TEAM_MEMBERS = 'j_id_jsp_345370874_1:tbEquipe'

ID_TEAM_MEMBERS_PRE_FIX = "//*[contains(@id, 'j_id_jsp_')]//*[contains(@id, ':tbEquipe:tbody_element')]/tr["
ID_TEAM_MEMBERS_POS_FIX_NAME = ']/td[1]'
ID_TEAM_MEMBERS_POS_FIX_CATEGORY = ']/td[2]'
ID_TEAM_MEMBERS_POS_FIX_FUNCTION = ']/td[3]'
ID_TEAM_MEMBERS_POS_FIX_DEPARTAMENT = ']/td[4]'
ID_TEAM_MEMBERS_POS_FIX_STATUS = ']/td[5]'

ID_TABLE_RELATORIO_PRE_FIX = "//*[contains(@id, 'j_id_jsp_')]/table[contains(@class, 'tabelaRelatorio')]/tbody/tr[";
ID_TABLE_RELATORIO_POS_FIX = "]/td"

# CURSO
# CURSO_IDS_MUNICIPIO_DE_REALIZACAO = 
# CURSO_IDS_ESPACO_DE_REALIZACAO = 
# CURSO_IDS_ABRANGENCIA = 
# CURSO_IDS_PUBLICO_ALVO = 
# CURSO_IDS_CURSO_IDS_UNIDADE_PROPONENTE = 
# CURSO_IDS_UNIDADE_ORCAMENTARIA = 
# CURSO_IDS_OUTRAS_UNIDADES_ENVOLVIDAS = 
# CURSO_IDS_AREA_PRINCIPAL = 
# CURSO_IDS_AREA_DO_CNPQ = 
# CURSO_IDS_FONTE_DE_FINANCIAMENTO = 
# CURSO_IDS_CONVENIO_FUNPEC =    
# CURSO_IDS_RENOVACAO = 
# CURSO_IDS_NUMERO_BOLSAS_SOLICITADAS =  
# CURSO_IDS_NUMERO_BOLSAS_CONCEDIDAS = 
# CURSO_IDS_NUMERO_DISCENTES_ENVOLVIDOS = 
# CURSO_IDS_FAZ_PARTE_DE_PROGRAMA_DE_EXTENSAO = 
# CURSO_IDS_PUBLICO_ESTIMADO =   
# CURSO_IDS_PUBLICO_REAL_ATENDIDO = 
# CURSO_IDS_CADASTRO_TIPO = 
# CURSO_IDS_CADASTRO_CATEGORIA = 
# CURSO_IDS_CADASTRO_SUBCATEGORIA = 
# CURSO_IDS_PERIODO_DE_EXECUCAO = 
# CURSO_IDS_CARGA_HORARIO = 
# CURSO_IDS_PREVISAO_N_DE_VAGAS = 

# CURSO_IDS_CONTATO_COORDENACAO = 
# CURSO_IDS_CONTATO_EMAIL = 
# CURSO_IDS_CONTATO_TELEFONE = 
